### ISSUE TITLE
No constructor

### ISSUE THREAD

**Issue by tarang9211** [kyleclegg/FlickrSearch#1]
This might be because of the different versions of Swift that are available. In the FlickrDataProvider class, you seem to make a call to the init() method of FlickrPhoto.swift without explicitly defining the init() in FlickrPhoto.swift. 

Am I missing something or is this in error? Thanks!

**Comment by tarang9211** [comment]
Sorry about that, I just realized that you are using a struct instead of a class

**Comment by kyleclegg** [comment]
I've updated the project for Swift 2.2. That should help eliminate some confusion. 👍
